---
- hosts: default
  vars:
    timezone: "Asia/Tokyo"
    nodesource: https://rpm.nodesource.com/setup_8.x
    app_nginx_conf_src: "/vagrant/vagrant-conf/nginx-vagrant.conf"
    app_nginx_conf_dest: /etc/nginx/default.d/vagrant.conf
  tasks:
    - block:
      - block:
        - name: Check timezone
          shell: timedatectl | grep -e {{ timezone }}
          register: timedatectl_timezone
          check_mode: no
          changed_when: false
          failed_when: false
        - name: Set timezone
          shell: timedatectl set-timezone {{ timezone }}
          when: timedatectl_timezone.stdout == ""
      - block:
        - name: Check Node.js repository version
          shell: yum info nodejs | grep -e "Version\s*:\s*[8-9].*$"
          register: nodejs_repository_version
          check_mode: no
          changed_when: false
          failed_when: false
        - name: Register Node.js repository
          shell: curl --silent --location {{ nodesource }} | bash -
          when: nodejs_repository_version.stdout == ""
        - name: Upgrade all packages
          yum: name=* state=latest
        - name: Install the latest version of Node.js
          yum: name=nodejs state=latest
        - name: Install the latest version of MariaDB
          yum: name=mariadb state=latest
        - name: Install the latest version of MariaDB server
          yum: name=mariadb-server state=latest
        - name: Install the latest version of MySQL-python
          yum: name=MySQL-python state=latest
        - name: Install the latest version of nginx
          yum: name=nginx state=latest
        - name: Install the latest version of Git
          yum: name=git state=latest
      - block:
        - name: Install "mocha" node.js package globally
          npm: name=mocha global=yes
        - name: Install "pm2" node.js package globally
          npm: name=pm2 global=yes
        - name: Install "webpack" node.js package globally
          npm: name=webpack global=yes
        - name: Install "typescript" node.js package globally
          npm: name=typescript global=yes
        - name: Install "typedoc" node.js package globally
          npm: name=typedoc global=yes
        - name: Install "tslint" node.js package globally
          npm: name=tslint global=yes
        - name: Install "node-pre-gyp" node.js package globally
          npm: name=node-pre-gyp global=yes
      - block:
        - name: Action to enable service mariadb
          service: name=mariadb state=started enabled=yes
        - name: Copy the web app configuration to nginx
          copy: src={{ app_nginx_conf_src }} dest={{ app_nginx_conf_dest }} force=no
        - name: Action to enable service nginx
          service: name=nginx state=restarted enabled=yes
      - block:
        - name: Action to disable SELinux for nginx
          selinux: state=permissive policy=targeted
        - name: Action to enable service firewalld
          service: name=firewalld state=started enabled=yes
        - name: Open port for HTTP
          firewalld: service=http permanent=true state=enabled
        - name: Open port for MariaDB only internal zone
          firewalld: service=mysql permanent=true state=enabled zone=internal
        - name: Set private ip addresses to internal zone
          firewalld: source='172.16.0.0/12' zone=internal state=enabled
        - name: Action to reload service firewalld
          service: name=firewalld state=reloaded enabled=yes
      - block:
        - name: Check "pm2" service registration
          shell: systemctl status pm2-vagrant.service | grep -e "enabled"
          register: pm2_service_loaded
          check_mode: no
          changed_when: false
          failed_when: false
        - name: Register "pm2" to service by vagrant user
          shell: pm2 startup systemd -u vagrant --hp /home/vagrant
          when: pm2_service_loaded.stdout == ""
        - name: Action to enable service pm2
          service: name=pm2-vagrant state=started enabled=yes
      become: true
