---
- name: Install Remi repository
  yum: name={{ remi_repository }}
- name: Install the latest version of yum-utils
  yum: name=yum-utils state=latest
- name: Check PHP version
  shell: yum info php | grep -e "Version\s*:\s*7\."
  register: php_version
  check_mode: no
  changed_when: false
  failed_when: false
- name: Enable Remi repository
  shell: yum-config-manager --enable "{{ remi_repository_name }}"
  when: php_version.stdout == ""
- name: Install the latest version of PHP7
  yum: name=php state=latest
- name: Install the latest version of php-pdo
  yum: name=php-pdo state=latest
- name: Install the latest version of php-mysqlnd
  yum: name=php-mysqlnd state=latest
- name: Install the latest version of php-mbstring
  yum: name=php-mbstring state=latest
- name: Install the latest version of php-xml
  yum: name=php-xml state=latest
- name: Install the latest version of php-intl
  yum: name=php-intl state=latest
- name: Install Composer
  get_url:
    url: "{{ composer_phar_url }}"
    dest: /usr/local/bin/composer
    mode: 0555
- name: Copy php application configuration to Apache
  template:
    src: "{{ php_apache_conf_src }}"
    dest: "{{ php_apache_conf_dest }}"
    force: no