# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "172.16.10.18"
  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "vagrant-conf/playbook.yml"
    ansible.provisioning_path = "/vagrant/"
  end

  config.vm.provision "shell", run: "always" do |s|
    s.inline = "sudo systemctl restart pm2"
  end
end
